[book]
title = "csv-to-parquet"
authors = ["Gildas Cadin"]
language = "fr"
description = "Convertisseur multi-format vers Parquet en Rust"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
edit-url-template = "https://github.com/gildas-le-drogoff/csv_to_parquet/edit/main/{path}"
git-repository-url = "https://github.com/gildas-le-drogoff/csv_to_parquet"
site-url = "/csv_to_parquet/"

[output.html.search]
limit-results = 30
teaser-word-count = 15

[output.html.fold]
enable = true
level = 1

[rust]
edition = "2021"
